spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-serviceV1"
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8080
